using Wayfinder.Core.Constants;
using Wayfinder.Core.DomainModels.Stats;
using Wayfinder.Core.Interfaces;
using Wayfinder.Core.Models.Characters;
using Wayfinder.Core.Models.Items;

namespace Wayfinder.Core.Engines;

public class EquipmentEngine : IEquipmentEngine
{
    public EquipmentSlot[] ArmorSlots { get; } = { EquipmentSlot.Armor };

    public EquipmentSlot[] RingSlots { get; } = { EquipmentSlot.Ring1, EquipmentSlot.Ring2 };

    public EquipmentSlot[] WondrousSlots { get; } = {
        EquipmentSlot.Head, EquipmentSlot.Headband, EquipmentSlot.Eyes,
        EquipmentSlot.Shoulders, EquipmentSlot.Neck, EquipmentSlot.Chest,
        EquipmentSlot.Body, EquipmentSlot.Belt, EquipmentSlot.Wrists,
        EquipmentSlot.Hands, EquipmentSlot.Feet
    };

    // Combine them dynamically so we don't have to maintain two separate lists
    public EquipmentSlot[] StandardBodySlots =>
        ArmorSlots.Concat(RingSlots).Concat(WondrousSlots).ToArray();

    public IEnumerable<ItemInstance> GetItemsByType(IEnumerable<ItemInstance> inventory, ItemType type)
    {
        return inventory.Where(i => i.BaseStats.Type == type);
    }

    public ItemInstance? GetItemInSlot(IEnumerable<ItemInstance> inventory, EquipmentSlot slot)
    {
        return inventory.FirstOrDefault(i => i.EquippedSlot == slot);
    }

    public IEnumerable<ItemInstance> GetEquippableItemsForSlot(IEnumerable<ItemInstance> inventory, EquipmentSlot targetSlot)
    {
        return inventory.Where(i =>
            (i.EquippedSlot == targetSlot || i.State == ItemState.Carried) &&
            IsSlotCompatible(i.BaseStats.Slot, targetSlot)
        );
    }

    public bool IsSlotCompatible(EquipmentSlot? itemSlot, EquipmentSlot targetSlot)
    {
        if (itemSlot == null) return false;
        if (itemSlot == targetSlot) return true;

        if ((itemSlot == EquipmentSlot.Ring1 || itemSlot == EquipmentSlot.Ring2) &&
            (targetSlot == EquipmentSlot.Ring1 || targetSlot == EquipmentSlot.Ring2)) return true;

        if ((itemSlot == EquipmentSlot.MainHand || itemSlot == EquipmentSlot.OffHand) &&
            (targetSlot == EquipmentSlot.MainHand || targetSlot == EquipmentSlot.OffHand)) return true;

        return false;
    }

    // Add this new method to rebuild effects from scratch
    public void RebuildEquipmentEffects(CharacterSheet sheet)
    {
        // 1. Remove all existing effects that came from inventory items to prevent duplicates
        var inventoryIds = sheet.Inventory.Select(i => i.Id).ToHashSet();
        sheet.ActiveEffects.RemoveAll(e => inventoryIds.Contains(e.SourceId));

        // 2. Re-apply effects for everything currently marked as equipped
        var equippedItems = sheet.Inventory.Where(i => i.State == ItemState.Equipped);
        foreach (var item in equippedItems)
        {
            ApplyItemEffects(sheet, item);
        }
    }

    // Extract the effect generation into a helper so we don't repeat ourselves
    private void ApplyItemEffects(CharacterSheet sheet, ItemInstance item)
    {
        if (item.BaseStats is ArmorItem armor && armor.ArmorBonus > 0)
        {
            sheet.ActiveEffects.Add(new ActiveEffect
            {
                SourceId = item.Id,
                SourceName = armor.Name,
                Category = EffectCategory.Item,
                TargetStatName = StatNames.AC,
                Value = armor.ArmorBonus,
                Type = ModifierType.Armor
            });
        }
        else if (item.BaseStats is ShieldItem shield && shield.ShieldBonus > 0)
        {
            sheet.ActiveEffects.Add(new ActiveEffect
            {
                SourceId = item.Id,
                SourceName = shield.Name,
                Category = EffectCategory.Item,
                TargetStatName = StatNames.AC,
                Value = shield.ShieldBonus,
                Type = ModifierType.Shield
            });
        }
    }

    public void EquipItem(CharacterSheet sheet, ItemInstance item, EquipmentSlot slot)
    {
        var existingItem = GetItemInSlot(sheet.Inventory, slot);
        if (existingItem != null)
        {
            UnequipItem(sheet, existingItem);
        }

        item.State = ItemState.Equipped;
        item.EquippedSlot = slot;
        item.ContainerId = null;

        ApplyItemEffects(sheet, item);
    }

    public void UnequipSlot(CharacterSheet sheet, EquipmentSlot slot)
    {
        var currentItem = GetItemInSlot(sheet.Inventory, slot);
        if (currentItem != null)
        {
            UnequipItem(sheet, currentItem);
        }
    }

    public void UnequipItem(CharacterSheet sheet, ItemInstance item)
    {
        // 1. Change item state
        item.State = ItemState.Carried;
        item.EquippedSlot = null;

        // 2. Remove all Active Effects generated by this exact item instance
        sheet.ActiveEffects.RemoveAll(e => e.SourceId == item.Id);
    }


}
