name: Tests

on:
  pull_request:
  push:
    branches: [ "master", "main" ]

  workflow_dispatch:

jobs:
  build-and-test:

    name: Build and Test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        # os: [ubuntu-latest, windows-latest]
        #os: [ubuntu-latest]
    env:
        PROJECT_NAME: Wayfinder
        DOTNET_VERSION: 10.x.x
        CODE_ROOT_PATH: ./Wayfinder

    steps:
      - name: Checkout code
        uses: actions/checkout@v5


      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI Workload(s)
        run: dotnet workload restore ${{ env.CODE_ROOT_PATH }}/${{ env.PROJECT_NAME }}.slnx
        
      - name: Install dependencies
        run: dotnet restore ${{ env.CODE_ROOT_PATH }}/${{ env.PROJECT_NAME }}.slnx -r win-x64
        
      - name: Build
        run: dotnet build ${{ env.CODE_ROOT_PATH }}/${{ env.PROJECT_NAME }}.slnx --configuration Release --no-restore -r win-x64
      
      - name: Test
        run: dotnet test ${{ env.CODE_ROOT_PATH }}/${{ env.PROJECT_NAME }}.slnx --no-restore --verbosity normal

      - name: Check Formatting
        run: dotnet format ${{ env.CODE_ROOT_PATH}}/${{ env.PROJECT_NAME }}.slnx --verify-no-changes --verbosity diagnostic
